<?php

namespace User\UserRepository;


class Statuses
{
    const SUCCESS = 1;

    const ERROR_EMPTY_FIELDS = 2;

    const ERROR_PASSWORDS_MISMATCH = 4;
    const ERROR_PASSWORD_LENGTH = 8;
    const ERROR_PASSWORD_WHITESPACES = 16;
    const ERROR_PASSWORD_WEAK = 32;

    const ERROR_EMAIL_INVALID = 64;

    const ERROR_LOGIN_ILLEGAL_CHARACTERS = 128;
    const ERROR_LOGIN_LENGTH = 256;

    const ERROR_NICK_ILLEGAL_CHARACTERS = 512;
    const ERROR_NICK_LENGTH = 1024;

    const ERROR_LOGIN_ALREADY_EXISTS = 2048;
    const ERROR_NICK_ALREADY_EXISTS = 4096;
}
